# AI-Based Disease Prediction System
### Models:
- Diabetes Prediction
- Heart Disease Prediction
- COVID-19 Prediction

This project uses Machine Learning (Random Forest) to predict diseases based on medical attributes.

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
diabetes = pd.read_csv("diabetes.csv")
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
print(diabetes.shape)
print(diabetes.info())
print(diabetes.isnull().sum())

(768, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB
None
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
X = diabetes.drop("Outcome", axis=1)
y = diabetes["Outcome"]

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=1200,
    max_depth=5,
    min_samples_split=12,
    min_samples_leaf=5,
    class_weight='balanced_subsample',
    random_state=42
)
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', model)
])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7467532467532467
[[74 26]
 [13 41]]
              precision    recall  f1-score   support

           0       0.85      0.74      0.79       100
           1       0.61      0.76      0.68        54

    accuracy                           0.75       154
   macro avg       0.73      0.75      0.73       154
weighted avg       0.77      0.75      0.75       154

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(pipeline, X, y, cv=5)
print(scores)
print(scores.mean())

[0.74025974 0.71428571 0.78571429 0.82352941 0.75163399]
0.7630846277905101

In [ ]:
print("Train Score:", pipeline.score(X_train, y_train))
print("Test Score:", pipeline.score(X_test, y_test))

Train Score: 0.8403908794788274
Test Score: 0.7467532467532467

In [ ]:
import joblib

joblib.dump(pipeline, "diabetes_model.pkl")

['diabetes_model.pkl']

In [ ]:
def predict_diabetes(input_data):
    prediction = pipeline.predict([input_data])
    return prediction[0]

In [ ]:
sample = [5, 150, 80, 30, 0, 33.5, 0.6, 45]

print(predict_diabetes(sample))

1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
heart = pd.read_csv("heart.csv")
heart.head()

,AGE_50,MD_50,SBP_50,DBP_50,HT_50,WT_50,CHOL_50,SES,CL_STATUS,MD_62,SBP_62,DBP_62,CHOL_62,WT_62,IHD_DX,DEATH
0,42,1,110,65,64,147,291,2,8,4,120,78,271,146,2,1
1,53,1,130,72,69,167,278,1,6,2,122,68,250,165,9,1
2,53,2,120,90,70,222,342,4,8,1,132,90,304,223,2,1
3,48,4,120,80,72,229,239,4,8,2,118,68,209,227,3,1
4,53,3,118,74,66,134,243,3,8,5,118,56,261,138,2,1

In [ ]:
print(heart.shape)
print(heart.info())
print(heart['DEATH'].value_counts())

(200, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   AGE_50     200 non-null    int64
 1   MD_50      200 non-null    int64
 2   SBP_50     200 non-null    int64
 3   DBP_50     200 non-null    int64
 4   HT_50      200 non-null    int64
 5   WT_50      200 non-null    int64
 6   CHOL_50    200 non-null    int64
 7   SES        200 non-null    int64
 8   CL_STATUS  200 non-null    int64
 9   MD_62      200 non-null    int64
 10  SBP_62     200 non-null    int64
 11  DBP_62     200 non-null    int64
 12  CHOL_62    200 non-null    int64
 13  WT_62      200 non-null    int64
 14  IHD_DX     200 non-null    int64
 15  DEATH      200 non-null    int64
dtypes: int64(16)
memory usage: 25.1 KB
None
DEATH
0    136
1     64
Name: count, dtype: int64

In [ ]:
X = heart.drop('DEATH', axis=1)
y = heart['DEATH']

In [ ]:
print(X_train.columns)
print(len(X_train.columns))

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')
8

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=800,
    max_depth=6,
    min_samples_split=10,
    min_samples_leaf=4,
    class_weight='balanced_subsample',
    random_state=42
)

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', model)
])

In [ ]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 RandomForestClassifier(class_weight='balanced_subsample',
                                        max_depth=6, min_samples_leaf=4,
                                        min_samples_split=10, n_estimators=800,
                                        random_state=42))])

In [ ]:
y_pred = pipeline.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7
[[24  3]
 [ 9  4]]
              precision    recall  f1-score   support

           0       0.73      0.89      0.80        27
           1       0.57      0.31      0.40        13

    accuracy                           0.70        40
   macro avg       0.65      0.60      0.60        40
weighted avg       0.68      0.70      0.67        40

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(pipeline, X, y, cv=5)

print(scores)
print(scores.mean())

[0.775 0.675 0.8   0.7   0.625]
0.7150000000000001

In [ ]:
joblib.dump(pipeline, "heart_model.pkl")

['heart_model.pkl']

In [ ]:
import joblib

loaded_model = joblib.load("heart_model.pkl")

# test prediction again
sample = X_test.iloc[0]
print("Prediction:", loaded_model.predict([sample]))

Prediction: [0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
print("FINAL HEART MODEL REPORT")
print("------------------------")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Cross Validation Mean:", scores.mean())
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

FINAL HEART MODEL REPORT
------------------------
Accuracy: 0.7
Cross Validation Mean: 0.7150000000000001

Confusion Matrix:
 [[24  3]
 [ 9  4]]

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.89      0.80        27
           1       0.57      0.31      0.40        13

    accuracy                           0.70        40
   macro avg       0.65      0.60      0.60        40
weighted avg       0.68      0.70      0.67        40

In [32]:
import pandas as pd

df = pd.read_csv("Covid Dataset.csv")
df.head()

,Breathing Problem,Fever,Dry Cough,Sore throat,Running Nose,Asthma,Chronic Lung Disease,Headache,Heart Disease,Diabetes,...,Fatigue,Gastrointestinal,Abroad travel,Contact with COVID Patient,Attended Large Gathering,Visited Public Exposed Places,Family working in Public Exposed Places,Wearing Masks,Sanitization from Market,COVID-19
0,Yes,Yes,Yes,Yes,Yes,No,No,No,No,Yes,...,Yes,Yes,No,Yes,No,Yes,Yes,No,No,Yes
1,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,No,No,...,Yes,No,No,No,Yes,Yes,No,No,No,Yes
2,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,...,Yes,Yes,Yes,No,No,No,No,No,No,Yes
3,Yes,Yes,Yes,No,No,Yes,No,No,Yes,Yes,...,No,No,Yes,No,Yes,Yes,No,No,No,Yes
4,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,...,No,Yes,No,Yes,No,Yes,No,No,No,Yes

In [33]:
df.info()
df['COVID-19'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5434 entries, 0 to 5433
Data columns (total 21 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Breathing Problem                        5434 non-null   object
 1   Fever                                    5434 non-null   object
 2   Dry Cough                                5434 non-null   object
 3   Sore throat                              5434 non-null   object
 4   Running Nose                             5434 non-null   object
 5   Asthma                                   5434 non-null   object
 6   Chronic Lung Disease                     5434 non-null   object
 7   Headache                                 5434 non-null   object
 8   Heart Disease                            5434 non-null   object
 9   Diabetes                                 5434 non-null   object
 10  Hyper Tension                            5434 non-null   object
 11  Fatigue                                  5434 non-null   object
 12  Gastrointestinal                         5434 non-null   object
 13  Abroad travel                            5434 non-null   object
 14  Contact with COVID Patient               5434 non-null   object
 15  Attended Large Gathering                 5434 non-null   object
 16  Visited Public Exposed Places            5434 non-null   object
 17  Family working in Public Exposed Places  5434 non-null   object
 18  Wearing Masks                            5434 non-null   object
 19  Sanitization from Market                 5434 non-null   object
 20  COVID-19                                 5434 non-null   object
dtypes: object(21)
memory usage: 891.6+ KB

COVID-19
Yes    4383
No     1051
Name: count, dtype: int64

In [34]:
X = df.drop("COVID-19", axis=1)
y = df["COVID-19"]

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [36]:
from sklearn.preprocessing import LabelEncoder

for col in X_train.columns:
    if X_train[col].dtype == 'object':
        le = LabelEncoder()
        X_train[col] = le.fit_transform(X_train[col])
        X_test[col] = le.transform(X_test[col])

In [37]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=800,
    max_depth=6,
    min_samples_split=10,
    min_samples_leaf=4,
    class_weight='balanced_subsample',
    random_state=42
)

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', model)
])

In [38]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 RandomForestClassifier(class_weight='balanced_subsample',
                                        max_depth=6, min_samples_leaf=4,
                                        min_samples_split=10, n_estimators=800,
                                        random_state=42))])

In [39]:
y_pred = pipeline.predict(X_test)

In [40]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9659613615455381
[[201   9]
 [ 28 849]]
              precision    recall  f1-score   support

          No       0.88      0.96      0.92       210
         Yes       0.99      0.97      0.98       877

    accuracy                           0.97      1087
   macro avg       0.93      0.96      0.95      1087
weighted avg       0.97      0.97      0.97      1087

In [41]:
joblib.dump(pipeline, "covid_model.pkl")

['covid_model.pkl']

In [42]:
import joblib

diabetes_model = joblib.load("diabetes_model.pkl")
heart_model = joblib.load("heart_model.pkl")
covid_model = joblib.load("covid_model.pkl")

In [43]:
def predict_diabetes(input_data):
    return diabetes_model.predict([input_data])[0]

In [44]:
def predict_heart(input_data):
    return heart_model.predict([input_data])[0]

In [45]:
def predict_covid(input_data):
    return covid_model.predict([input_data])[0]

In [46]:
def predict_disease(disease, input_data):
    if disease == "diabetes":
        return predict_diabetes(input_data)
    elif disease == "heart":
        return predict_heart(input_data)
    elif disease == "covid":
        return predict_covid(input_data)
    else:
        return "Invalid disease type"

In [47]:
# print(X.columns)
# Pregnancies
# Glucose
# BloodPressure
# SkinThickness
# Insulin
# BMI
# DiabetesPedigreeFunction
# Age
sample_diabetes_input = [2, 120, 70, 20, 80, 25.5, 0.5, 30]

In [48]:
# age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal
sample_heart_input = [45, 1, 2, 130, 230, 0, 1, 150, 0, 2.3, 1, 0, 2, 0, 1]

In [49]:
# fever, cough, fatigue, breathlessness, etc
sample_covid_input = [0, 0, 0, 0, 1,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 1, 1, 1]

In [50]:
print(predict_disease("diabetes", sample_diabetes_input))
print(predict_disease("heart", sample_heart_input))
print(predict_disease("covid", sample_covid_input))

0
1
No

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(